//      *********    DO NOT MODIFY THIS FILE     *********
//      This file is regenerated by a design tool. Making
//      changes to this file can cause errors.
namespace Telerik.Windows.Examples
{
	using System;
    using System.Linq; 

// To significantly reduce the sample data footprint in your production application, you can set
// the DISABLE_SAMPLE_DATA conditional compilation constant and disable sample data at runtime.
#if DISABLE_SAMPLE_DATA
	internal class Northwind { }
#else

    public partial class Northwind
	{
		private Order_DetailsCollection _Order_DetailsCollection;

		public Order_DetailsCollection Order_DetailsCollection
		{
			get
			{
                if(this._Order_DetailsCollection == null)
                {
                    this._Order_DetailsCollection = new Order_DetailsCollection();

                    System.Uri resourceUri = new System.Uri("/GridView;component/SampleData/Order_DetailsSampleDataSource/Order_DetailsSampleDataSource.xaml", System.UriKind.Relative);
			        if (System.Windows.Application.GetResourceStream(resourceUri) != null)
			        {
				        System.Windows.Application.LoadComponent(this, resourceUri);
			        }
                }
				return this._Order_DetailsCollection;
			}
		}
	}

	public partial class Order_Detail : System.ComponentModel.INotifyPropertyChanged
	{
        static Northwind _Northwind;
        public static Northwind Northwind
        {
            get
            {
                if (_Northwind == null)
                {
                    _Northwind = new Northwind();
                }

                return _Northwind;
            }
        }

        Products product;

        [System.ComponentModel.Browsable(false)]
        public Products Product
        {
            get
            {
                if (product == null)
                {
                    product = (from o in Northwind.ProductsCollection
                               where o.ProductID == ProductID
                               select o).FirstOrDefault();
                }

                return product;
            }
        }

		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		private double _OrderID = 0;

		public double OrderID
		{
			get
			{
				return this._OrderID;
			}

			set
			{
				if (this._OrderID != value)
				{
					this._OrderID = value;
					this.OnPropertyChanged("OrderID");
				}
			}
		}

		private double _ProductID = 0;

		public double ProductID
		{
			get
			{
				return this._ProductID;
			}

			set
			{
				if (this._ProductID != value)
				{
					this._ProductID = value;
					this.OnPropertyChanged("ProductID");
				}
			}
		}

		private double _UnitPrice = 0;

		public double UnitPrice
		{
			get
			{
				return this._UnitPrice;
			}

			set
			{
				if (this._UnitPrice != value)
				{
					this._UnitPrice = value;
					this.OnPropertyChanged("UnitPrice");
				}
			}
		}

		private double _Quantity = 0;

		public double Quantity
		{
			get
			{
				return this._Quantity;
			}

			set
			{
				if (this._Quantity != value)
				{
					this._Quantity = value;
					this.OnPropertyChanged("Quantity");
				}
			}
		}

		private double _Discount = 0;

		public double Discount
		{
			get
			{
				return this._Discount;
			}

			set
			{
				if (this._Discount != value)
				{
					this._Discount = value;
					this.OnPropertyChanged("Discount");
				}
			}
		}
	}

	public class Order_DetailsCollection : System.Collections.ObjectModel.ObservableCollection<Order_Detail>
	{ 
	}
#endif
}
